spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10 # 요청 개수 및 시간으로 지정 가능
        minimumNumberOfCalls: 5 # 실패율과 느린 응답 비율 계산할 최소 요청 수
        permittedNumberOfCallsInHalfOpenState: 3 # 회로가 half-open-open 상태일 때 받아 들일 요청 수
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s # open에서 half-open 상태로 넘어가며 기다리는 시간
        failureRateThreshold: 50 # 해당 비율 넘을 경우 회로 차단
    instances:
      customCircuitBreaker:
        baseConfig: default

login-info:
  naver-client-id: ${NAVER_CLIENT_ID}
  naver-client-secret: ${NAVER_CLIENT_SECRET}
  kakao-secret: ${KAKAO_REST_API_KEY}
